### ISSUE TITLE
当请求失败是无法直接获取错误代码

### ISSUE THREAD

**Issue by uyson** [LeeHom1988/iOS_IAP_Verification_PHP#2]

**Comment by iamleehom** [comment]
> _No description provided._

不知道你指的请求失败是指那方面的请求失败？
网络失败？
苹果服务器返回的失败？
对于前者，用户可以选择自行捕获网络失败错误码。
对于后者，这个库返回的是详细的报错信息，并不是错误码。
如有必要，请补充请求失败详细信息。

**Comment by uyson** [comment]
在函数validateReceipt， 当status不等于0 的时候回返回一个字符串， 不能直接获取status

**Comment by sgaykhe** [comment]
Hi,
tried running the code it gave me error, i dont have the base64 code =, can ypu guide me how to get it from apple.
I have the numeric transaction ID i receive it from apple.
Please Help

**Comment by iamleehom** [comment]
> Hi,
> tried running the code it gave me error, i dont have the base64 code =, can ypu guide me how to get it from apple.
> I have the numeric transaction ID i receive it from apple.
> Please Help

Hi, 
You can follow this way to get the base64 code:
https://developer.apple.com/documentation/appstorereceipts/responsebody

**Comment by iamleehom** [comment]
> 在函数validateReceipt， 当status不等于0 的时候回返回一个字符串， 不能直接获取status
你好，

目前是这样的，当验证不通过时返回的是错误描述信息。
