### ISSUE TITLE
缺少参数exclude-old-transactions

### ISSUE THREAD

**Issue by uyson** [LeeHom1988/iOS_IAP_Verification_PHP#3]
请求时缺少参数 exclude-old-transactions
https://developer.apple.com/documentation/appstorereceipts/requestbody

**Comment by iamleehom** [comment]
> 请求时缺少参数 exclude-old-transactions
> https://developer.apple.com/documentation/appstorereceipts/requestbody

（exclude-old-transactions）此参数为非必填参数，且仅在订阅支付类型时生效，并不影响实际支付校验结果，有需要你可以选择自行扩展或后期我更新一个版本。
